---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrom-pvc
  namespace: retrom-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: retrom-pgdb-pvc
  namespace: retrom-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
