---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: servarr-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: cluster
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 0.0.8
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system

  values:
    cluster:
      instances: 3
      storage:
        size: 8Gi
        storageClass: ""
      monitoring:
        # -- Whether to enable monitoring
        enabled: true
