---
apiVersion: traefik.containo.us/v1alpha1
kind: IngressRouteTCP
metadata:
  name: servarr-ingress-tcp
  namespace: servarr-ns
  #labels:
  #  app: minecraft-minecraft

spec:
  entryPoints:
    - postgres
  routes:
    - match: HostSNI(`*`)
      services:
        - name: postgres
          port: 5432
