---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
  namespace: calibre
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
