---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-web-config-pvc
  namespace: calibre-web-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: calibre-web-books-pvc
#  namespace: calibre-web-ns
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: nfs-client
#  resources:
#    requests:
#      storage: 10Gi
