---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre-web
  namespace: calibre-web-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre-web
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/New York"
    service:
      main:
        ports:
          http:
            port: 8083
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: calibre-web-config-pvc
      books:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/calibre-taurus
