apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.11.10-192.168.11.255
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 192.168.11.2-192.168.11.9
  # This pool is special addresses, don't hand them out unless asked for
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
