---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: jellyseer
  namespace: jellyseer-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 1.5.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: fallenbagel/jellyseerr
      pullPolicy: IfNotPresent
      tag: 1.7.0

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 5055

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        mountPath: /app/config
        existingClaim: jellyseer-config-pvc
