---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyseer-config-pvc
  namespace: jellyseer-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
