---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: esphome
  namespace: home-automation-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 2.2.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/esphome/esphome
              tag: 2023.12.5
              pullPolicy: IfNotPresent

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"
      ESPHOME_DASHBOARD_USE_PING: true

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 6052

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /config
        existingClaim: esphome-pvc
