#---
#apiVersion: v1
#kind: PersistentVolumeClaim
#metadata:
#  name: semaphore-pvc
#  namespace: semaphore-ns
#spec:
#  accessModes:
#    - ReadWriteMany
#  storageClassName: nfs-client
#  resources:
#    requests:
#      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: semaphore-pgdb-pvc
  namespace: semaphore-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
