---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: semaphore
  namespace: semaphore-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 2.2.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        containers:
          main:
            image:
              repository: semaphoreui/semaphore
              tag: latest
              pullPolicy: IfNotPresent
            env:
              SEMAPHORE_DB_USER: semaphore
              SEMAPHORE_DB_PASS: semaphore
              SEMAPHORE_DB_HOST: semaphore-pgdb
              SEMAPHORE_DB_PORT: 5432
              SEMAPHORE_DB_DIALECT: postgres
              SEMAPHORE_DB: semaphore
              SEMAPHORE_PLAYBOOK_PATH: /tmp/semaphore/
              SEMAPHORE_ADMIN_PASSWORD: sdfwer234
              SEMAPHORE_ADMIN_NAME: admin
              SEMAPHORE_ADMIN_EMAIL: brendonmccool@gmail.com
              SEMAPHORE_ADMIN: admin
              SEMAPHORE_ACCESS_KEY_ENCRYPTION: Op0oN0dYsOHxqSM3+8eV35BhPfD+6Zkhoraj+v0ERns=
              SEMAPHORE_LDAP_ACTIVATED: 'no' # if you wish to use ldap, set to: 'yes'
              SEMAPHORE_LDAP_HOST: dc01.local.example.com
              SEMAPHORE_LDAP_PORT: '636'
              SEMAPHORE_LDAP_NEEDTLS: 'yes'
              SEMAPHORE_LDAP_DN_BIND: 'uid=bind_user,cn=users,cn=accounts,dc=local,dc=shiftsystems,dc=net'
              SEMAPHORE_LDAP_PASSWORD: 'ldap_bind_account_password'
              SEMAPHORE_LDAP_DN_SEARCH: 'dc=local,dc=example,dc=com'
              SEMAPHORE_LDAP_SEARCH_FILTER: "(\u0026(uid=%s)(memberOf=cn=ipausers,cn=groups,cn=accounts,dc=local,dc=example,dc=com))"
              TZ: "America/New York"
      pgdb:
        containers:
          main:
            image:
              repository: postgres
              tag: 16
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New York"
              POSTGRES_USER: semaphore
              POSTGRES_PASSWORD: semaphore
              POSTGRES_DB: semaphore

    strategy:
      type: Recreate

    # -- Configures service settings for the chart.
    service:
      main:
        controller: main
        ports:
          http:
            port: 3000
      pgdb:
        controller: pgdb
        type: NodePort
        ports:
          http:
            port: 5432
            targetPort: 5432
            protocol: TCP
            nodePort: 5433


    # -- Configure persistence settings for the chart under this key.
    persistence:
      #config:
      #  enabled: true
      #  existingClaim: semaphore-pvc
      #  advancedMounts:
      #    main:
      #      main:
      #        - path: /config
      data:
        enabled: true
        existingClaim: semaphore-pgdb-pvc
        advancedMounts:
          pgdb:
            main:
              - path: /var/lib/postgresql/data
