---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarr
  namespace: sonarr-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 3.1.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        enabled: true
        # Valid options are deployment, daemonset, statefulset, cronjob or job
        type: deployment
        annotations: {}
        labels: {}
        replicas: 1
        # strategy:
        #   type: Recreate
        containers:
          main:
            image:
              repository: linuxserver/sonarr
              tag: 4.0.4
              pullPolicy: IfNotPresent
            env:
              TZ: "America/New York"
        initContainers:
          - name: restore-db
            image:
              repository: busybox
              tag: latest
            command: ["cp", "-rfv", "/persistent-config", "/config"]
    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 8989

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        type: persistentVolumeClaim
        enabled: true
        globalMounts:
          - path: /persistent-config
        existingClaim: sonarr-config-pvc
      done:
        type: nfs
        server: NFS.brendonmccool.com
        path: /k8s/torrents-taurus/done/sonarr
        globalMounts:
          - path: /done
      tv:
        type: nfs
        server: NFS.brendonmccool.com
        path: /media/tv
        globalMounts:
          - path: /tv
