---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: 1.25.0
#TODO
clusterName: kubernetes
# controlPlaneEndpoint can be ip address or dns subdomain, both with optional TCP port, if not specified advertiseAddress + bindport are used
#TODO
controlPlaneEndpoint: "{{ controlplane_endpoint_ipaddress }}"
apiServer:
  #timeoutForControlPlane: 4m0s
  #TODO
  certSANs: 
    - "{{ controlplane_endpoint_ipaddress }}"
networking:
  dnsDomain: cluster.local
  #serviceSubnet: 10.244.0.0/16
  podSubnet: 10.244.0.0/16
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: "systemd"
#protectKernelDefaults: true
---
kind: InitConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
#TODO
certificateKey: "{{ certkey.stdout }}"
nodeRegistration:
  #criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  #TODO
  name: gemini-ctrl-1
  #taints: null