---
kind: ClusterConfiguration
apiVersion: kubeadm.k8s.io/v1beta3
kubernetesVersion: 1.24.3
# TODO
clusterName: "{{ cluster_friendly_name }}"
controlPlaneEndpoint: "{{ controlplane_endpoint_ipaddress }}"
apiServer:
  # timeoutForControlPlane: 4m0s
  certSANs:
    - "{{ controlplane_endpoint_ipaddress }}"
  # Expand node port range for minecraft according to https://hub.docker.com/r/itzg/mc-router
  extraArgs:
    service-node-port-range: 80-32767
networking:
  dnsDomain: cluster.local
  # serviceSubnet: 10.244.0.0/16
  podSubnet: "{{ pod_network_cidr }}"
---
kind: KubeletConfiguration
apiVersion: kubelet.config.k8s.io/v1beta1
cgroupDriver: "systemd"
# protectKernelDefaults: true
---
apiVersion: kubeadm.k8s.io/v1beta3
kind: InitConfiguration
nodeRegistration:
  # criSocket: unix:///var/run/containerd/containerd.sock
  imagePullPolicy: IfNotPresent
  # TODO
  name: "{{ hostname_result.stdout }}"
  # taints: null
  localAPIEndpoint:
    advertiseAddress: "{{ ip_result.stdout }}"
    bindPort: 6443
certificateKey: "{{ certkey.stdout }}"
