---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mealie
  namespace: mealie-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: mealie
      version: 5.1.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    api:
      env:
        TZ: "America/New York"
    env:
      TZ: "America/New York"
    service:
      main:
        ports:
          http:
            port: 3000
          api:
            enabled: true
            port: 9000
    persistence:
      api-data:
        enabled: true
        mountPath: /app/data
        existingClaim: mealie-pvc
