---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo-distributed
      version: 1.2.7
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 15m

  values:
    server:
      grpc_server_max_recv_msg_size: 8389000
      grpc_server_max_send_msg_size: 8389000
    querier:
      config:
        frontend_worker:
          gprc_client_config:
            max_send_msg_size: 8389000

    storage:
      trace:
        backend: s3
        s3:
          # This comes from minio web interface / access-keys
          access_key: '2RmGgy7DuuUwscLv'
          secret_key: '24IA2Vq2VhZ4PwmdDCv938jW3RJtqirJ'
          # I created this bucket too
          bucket: 'tempo-traces'
          endpoint: 'minio.brendonmccool.com:9000'
          insecure: true
    traces:
      otlp:
        grpc:
          enabled: true
          max_recv_msg_size_mib: 8
        http:
          enabled: true
      zipkin:
        enabled: false
      jaeger:
        thriftHttp:
          enabled: false
      opencensus:
        enabled: false
