---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: tempo
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: tempo-distributed
      version: 6.52.4
      sourceRef:
        kind: HelmRepository
        name: grafana-charts
        namespace: flux-system
      interval: 15m

  values:
    storage:
      trace:
        backend: s3
        s3:
          # This comes from minio web interface / access-keys
          access_key: '2RmGgy7DuuUwscLv'
          secret_key: '24IA2Vq2VhZ4PwmdDCv938jW3RJtqirJ'
          bucket: 'tempo-traces'
          endpoint: 'minio.brendonmccool.com:9000'
          insecure: true
    minio:
      enabled: true
      mode: standalone
      rootUser: root
      rootPassword: sdfwer234
      buckets:
        # Default Tempo storage bucket.
        # Note: I did not create this via minio web interface
        - name: tempo-traces
          policy: none
          purge: false
    traces:
      otlp:
        grpc:
          enabled: true
        http:
          enabled: true
      zipkin:
        enabled: false
      jaeger:
        thriftHttp:
          enabled: false
      opencensus:
        enabled: false
