---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: otel-collector
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: opentelemetry-collector
      version: 0.51.0
      sourceRef:
        kind: HelmRepository
        name: open-telemetry-charts
        namespace: flux-system
      interval: 15m

  values:
    mode: deployment
    config:
      extensions:
        zpages:
          endpoint: 0.0.0.0:55679
      receivers:
        otlp:
          protocols:
            grpc:
              endpoint: 0.0.0.0:4317
            http:
              endpoint: 0.0.0.0:4318
      exporters:
        logging:
          verbosity: detailed
        otlp:
          endpoint: tempo-distributor:4317
          tls:
            insecure: true
      service:
        pipelines:
          logs:
            exporters:
              - otlp
              - logging
            receivers:
              - otlp
          metrics:
            exporters:
              - otlp
              - logging
            receivers:
              - otlp
          traces:
            exporters:
              - otlp
              - logging
            receivers:
              - otlp
    #resources:
    #  limits:
    #    cpu: 100m
    #    memory: 200M
