# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: traefik
stringData:
    api-key: ENC[AES256_GCM,data:6ZlGvIwRzurCjD2O8h+96Oy3pBOF6bUOquIC0YwfjnMTCDD1xQ==,iv:u7Y9kD1SET75xCBZyeal1PDShk0iUiUDzn6yOsxfbYo=,tag:dY7dtmIQMJ6Dz4t01lPU2g==,type:str]
    api-email: ENC[AES256_GCM,data:sskHDvuqUrWlfsAbmjTmAaI0wzI4zd0=,iv:MkfdIGJTjjARlDBxP7veAPPasBFLKdx964ztpw3Ow6E=,tag:wmkyU/Lp9yoUtq6dbz5b6Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1dukhexsa4w5vvupadlh5gfra6jhwh6nj2flrveks3zw2n30r0fnqmc879j
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBma0Y1T1RIUXNyRVpFd041
            OTczN2R0S0NudytIUitYRnhVWDNGd1FMN2pFCmxxUmtUdU5oaHRXd0pWVlE1bVZY
            K0lXK2hqU1pHdXFzOGVrSlRpUXFXTncKLS0tIEZLaDdBaTlKakRpZXFPajI0RitK
            QzYwTGhhSGhMZVgrTFA3eUhsalJERFUKXOW2A7DOqHJxtaEhZth46aYwQyNIdjnm
            Phwg/ZEsQrvb/hmnF5etWvHopJJ4Z594LNWHFyIky40wVRVwtURBKg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-07T02:40:12Z"
    mac: ENC[AES256_GCM,data:z0qFvxuQ6+Cx9LmzpVbQHdgF31hsQrBDJtxNKzxH9JVeUpunpJwE5pyftnOGYgZ63XZ8rdSRuIDFrmIGiKyJr19w0clnwi6tNsvncf77eChqkmcPnp5viJQ9KvRDa5VS0npDM/NmRS1iVF9kdBlJ41wK4US/E2UeZaOGUBsbhEo=,iv:riy/bO12/x2hUElA9qTNsRhJ6zMl5nlO62MRsJPB2lA=,tag:xuFebuupvYimu9i6UbdlrQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
