---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: traefik-config
  namespace: traefik
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
