---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: calibre-pvc
  namespace: calibre-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
