---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: calibre
  namespace: calibre-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: calibre
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/New York"
    persistence:
      config:
        enabled: true
        #mountPath: /config
        existingClaim: calibre-pvc
      books:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/calibre-taurus
    service:
      main:
        ports:
          http:
            port: 8080
      webserver:
        enabled: true
        type: ClusterIP
        ports:
          webserver:
            enabled: true
            port: 8081
            protocol: TCP
            targetPort: 8081
