---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: GitRepository
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  # https://github.com/k8s-at-home/template-cluster-k3s/issues/324
  #ssh://git@github.com/onedr0p/home-ops
  url: ssh://git@github.com/bmccool/Constellation

  ref:
    #TODO make dynamic
    branch: cancer
  secretRef:
    name: flux-git-auth

---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-cluster
  namespace: flux-system
spec:
  interval: 10m
  # Path ending in flux directory from git root
  path: ./cluster/flux
  prune: true
  wait: false
  sourceRef:
    kind: GitRepository
    name: flux-cluster
