---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: uptime-kuma-config
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 512Mi
