---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: uptime-kuma
  namespace: default
spec:
  interval: 15m
  chart:
    spec:
      chart: uptime-kuma
      version: 1.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    env:
      TZ: "America/New York"
    #persistence:
    #  data:
    #    enabled: true
    #    mountPath: /app/data
    #    existingClaim: uptime-kuma-config
