---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cnpg
  namespace: postgresql-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudnative-pg
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 0.21.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: cloudnative-pg-charts
        namespace: flux-system

  values:
    monitoring:
      podMonitorEnabled: true
      grafanaDashboard:
        create: true
