---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: netbootxyz
  namespace: netbootxyz-ns
spec:
  install:
    remediation:
      retries: -1
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 2.2.0
      interval: 16m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        containers:
          main:
            image:
              repository: lscr.io/linuxserver/netbootxyz
              tag: latest
              pullPolicy: IfNotPresent

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"
      PUID: 1000
      PGID: 1000
      # MENU_VERSION=1.9.9 # Not used, pulling latest


    # -- Configures service settings for the chart.
    service:
      main: # Web Configuration Interface
        ports:
          http:
            port: 3000
      tftp:
        controller: main
        ports:
          http:
            port: 69
      #nginx_port: # not really used, this is for local caching hosting of images
      #  ports:
      #    http:
      #      port: 80


    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /config
        existingClaim: netbootxyz-config-pvc
