---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: transmission
  namespace: sonarr-transmission-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: transmission
      version: 8.4.2
      sourceRef:
        kind: HelmRepository
        name: k8s-at-home
        namespace: flux-system
      interval: 15m
  values:
    env:
      # -- Set the container timezone
      TZ: "America/New York"
      # -- Path in container where the Web UI is located
      TRANSMISSION_WEB_HOME: /web
      # -- Password to access the Web UI
      TRANSMISSION_RPC_PASSWORD: transmission
      TRANSMISSION_RPC_USERNAME: transmission
      TRANSMISSION_RPC_ENABLED: true
      TRANSMISSION_RPC_PORT: 9091
      TRANSMISSION_RPC_URL: /transmission/
      TRANSMISSION_RPC_AUTHENTICATION_REQUIRED: true
      # -- Torrent download directory
      TRANSMISSION_DOWNLOAD_DIR: /done
      # -- Enable incomplete download directory
      TRANSMISSION_INCOMPLETE_DIR_ENABLED: true
      # -- Incomplete download directory
      TRANSMISSION_INCOMPLETE_DIR: /incoming
      # -- Enable watch directory
      TRANSMISSION_WATCH_DIR_ENABLED: true
      # -- Watch directory
      TRANSMISSION_WATCH_DIR: /watch
    service:
      main:
        ports:
          http:
            port: 9091
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: sonarr-transmission-config-pvc
      watch:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/torrents-taurus/watch/sonarr
      incoming:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/torrents-taurus/incoming/sonarr
      done:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/torrents-taurus/done/sonarr
