---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sheetable-config
  namespace: sheetable-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 10Gi
