---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: 39.4.0
      sourceRef:
        kind: HelmRepository
        name: prometheus-community-charts
        namespace: flux-system
      interval: 15m
  install:
    createNamespace: true
    remediation:
      retries: 5
  upgrade:
    remediation:
      retries: 5
  values:
    defaultRules:
      create: true
      rules:
        etcd: false
        kubeScheduler: false
    kubeScheduler:
      enabled: false
    kubeEtcd:
      enabled: false
    alertmanager:
      enabled: true
    grafana:
      enabled: true
      adminPassword: prom-operator # Please change the default password in production !!!
    prometheusOperator:
      enabled: true
    prometheus:
      enabled: true
