---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-pvc
  namespace: stash-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-config-pvc
  namespace: stash-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
