---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: dashy
  namespace: dashy-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 1.3.2
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: lissy93/dashy
      pullPolicy: IfNotPresent
      tag: 2.1.1

    strategy:
      type: Recreate

    env:
      TZ: "America/New York"
      NODE_ENV: production
    service:
      main:
        ports:
          http:
            port: 80
    persistence:
      config:
        enabled: true
        mountPath: /app/public
        existingClaim: dashy-config-pvc
