---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: infrastructure
  namespace: flux-system
spec:
  interval: 10m
  dependsOn:
    - name: core
  # Path to infrastructure directory from flux directory
  path: ./cluster/infrastructure
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-cluster
  decryption:
    provider: sops
    secretRef:
      name: sops-age
