---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: influxdb
  namespace: monitoring
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 2.2.0
      interval: 20m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        containers:
          main:
            image:
              repository: influxdb
              tag: 2.7.5
              pullPolicy: IfNotPresent

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 8086

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        globalMounts:
          - path: /etc/influxdb2
        existingClaim: influxdb-config-pvc
      data:
        type: nfs
        server: NFS.brendonmccool.com
        path: /k8s/influxdb/capricorn
        globalMounts:
          - path: /var/lib/influxdb2
