apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  interval: 5m
  chart:
    spec:
      chart: metallb
      #version: "2.3.4"
      version: "4.0.0"
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
      interval: 1m
  #values:
  #  configInline:
  #    # The address-pools section lists the IP addresses that MetalLB is
  #    # allowed to allocate, along with settings for how to advertise
  #    # those addresses over BGP once assigned. You can have as many
  #    # address pools as you want.
  #    address-pools:
  #      - name: metallb-ipaddresspool
  #        # Protocol dictates how announcement is done, layer2 or bgp
  #        protocol: bgp
  #        # A list of IP address ranges over which MetalLB has
  #        # authority. You can list multiple ranges in a single pool, they
  #        # will all share the same settings. Each range can be either a
  #        # CIDR prefix, or an explicit start-end range of IPs.
  #        addresses:
  #          - 192.168.10.10-192.168.10.255
