# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: traefik
stringData:
    api-key: ENC[AES256_GCM,data:O7tPo4XJYwkoHVDpZcfOV/nEKxH6y7vJwUcuukn0VKRhfcc18Q==,iv:qk6h4h+COFxKR06ItNQGbx6nwy5Qazky30bFy0Pj+yA=,tag:ZFCV+PTaZ1UwxKR/NqSXTw==,type:str]
    api-email: ENC[AES256_GCM,data:rstSbwh9B2LCBJEzupXGnlCYQUwlDSk=,iv:M+EhX+0gni7r0pfk9N1shFhm+ZXCSo2Wi1tYXRj3PrI=,tag:d8giOIJtHIe0NilUlEk5rA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1y4fuzw4f4hgsf2e66qphslhqgcc27plk8hhjs4902rldgl28wyzsdnkss8
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDOFpWMlZ0VlgwNVlycXFY
            YXhpZ0owOXhLQllEby9hT200d3dyQ2FDYVNRClpRYnlnNXFGQ2d1NUJsS3pDWWNP
            Q3ZndENLNWYxbjduWXdZb3lwdkw5eE0KLS0tIEcwdTNFSEl1TTlpUS9XS2pVVSto
            dkxZOTM4SHE2alp5cVdoWXI1VSs1bDAKkcpsBw2I4FKyun1oz3JaBEH8l08gyyLD
            OrVDvPkqwTRX7aXtA9scgwc6lSv75ob2nEnVQKUFsaBJFFVEmhYLiQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-03-18T21:52:05Z"
    mac: ENC[AES256_GCM,data:JcMC9jkSG3hkR+ZmSXYczI65DW1d7GQK9b0PYQDa9KqgsTn1v7i54XXinHkHEuejqqIcC0ruphPjW2fTAODtQqmsQexDZUKHMfm/44V5d8AiJ2M3Oe+9zmj7tm2uZ/l48W19KrGRWKY44dXQ+VP72lOJvFPcem7hNJKn1gU7/Ug=,iv:ufb8gE2FSvGp67nqQ5fj8fUMXp1FfnFB2BvZoHIuxgY=,tag:kFjiPriFqTpi4c5nb24I5Q==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
