# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: traefik
stringData:
    api-key: ENC[AES256_GCM,data:pEzhenUr5/kJpyKzOJGCtu16m4VWw9FsHUfiU6v5TjIh2uPyrw==,iv:qp3oYdJi4OY3grVhWW7rZ1cTBMojCFMHhFHs+rNUW68=,tag:URG0tvWpXTea0h4rM6oJWw==,type:str]
    api-email: ENC[AES256_GCM,data:uE5p+t0NyIDYgk1iKPfY0GXJKJumeBk=,iv:c0ZaKXOxpE8LqjmIJON6SgToZx9qKjNvgUgVw3BV6wU=,tag:6iZ1DXVYh02TwRLjbawPIw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1krw75phkxu8pa9myfur64tk8qj5rzzksynuetzned8dmcrh9lejsqz9309
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4eW1GTTdscGdVKytZbkpH
            UCsvajFHeit5L0U5aHM3bjNQbHU5U1hFSjAwCnRlYkhMSGxSaTB5SHYvZjhwd0Zx
            cHBNNi9rYkJ4VXZLR0ZTdTM1bmxPbzQKLS0tIE45QXR3d3BEWWE1MmJRNlRZbDVk
            eGRyY1dKRmNOdDBtNzcxallXTUhORjQKkBMGQPUY/Mj7yijzH4Q8avKMKJKi/4p+
            i1NPE800ih6v7O2DaKiY+uKxhTitmvJ+B/bo5ldPdvFuVNv6nyi8sw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-01-16T11:52:02Z"
    mac: ENC[AES256_GCM,data:Reu3a1qkeOeDZJ07ACpwOxkSv0oa3RKamEUGDj2hmBxCRGyY3zwBRADZ2mvcz8bGsmDyZyG0aqqP89NOycsM3zJshVuqSkG78gVNejRF9KGCfKIzMxroHvgVMUxQ8Y9JVrxA3r5c1RHC2JEf8dtP1BfTsS4LDjWJK0l5gKbkLPE=,iv:woYnJVEBw0gEP0Po2HPLsElpRn8f6+Q6U9pmct3lA7E=,tag:OxzOyNCMUoQV9BUQhLJdbQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
