---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: homeassistant
  namespace: homeassistant-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 2.2.0
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:

    controllers:
      main:
        containers:
          main:
            image:
              repository: ghcr.io/home-assistant/home-assistant
              tag: 2024.1.3
              pullPolicy: IfNotPresent

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 8123

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        globalMounts:
          - path: /config
        existingClaim: homeassistant-pvc
