---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: lidarr
  namespace: lidarr-ns
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      # -- Version of the app-template helm chart
      # this example is not automatically updated, so be sure to use the latest chart version
      version: 0.1.1
      interval: 15m
      sourceRef:
        kind: HelmRepository
        name: bjw-s-helm-charts
        namespace: flux-system

  values:
    image:
      repository: linuxserver/lidarr
      pullPolicy: IfNotPresent
      tag: 1.2.6

    strategy:
      type: Recreate

    # -- environment variables.
    env:
      TZ: "America/New York"

    # -- Configures service settings for the chart.
    service:
      main:
        ports:
          http:
            port: 8686

    # -- Configure persistence settings for the chart under this key.
    persistence:
      config:
        enabled: true
        mountPath: /config
        existingClaim: lidarr-config-pvc
      music:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/media/music
      downloads:
        enabled: true
        type: nfs
        server: NFS.brendonmccool.com
        path: /mnt/k8s/torrents-taurus/lidarr/downloads/complete
