---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ss-storage-brendon-pvc
  namespace: strava-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ss-build-brendon-pvc
  namespace: strava-ns
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 1Gi
