apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: metallb-ipaddresspool
  namespace: metallb-system
spec:
  addresses:
    - 10.208.100.20-10.208.100.99
---
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: traefik-addresspool
  namespace: metallb-system
spec:
  addresses:
    - 10.208.100.2-10.208.100.19
  # This pool is special addresses, don't hand them out unless asked for
  autoAssign: false
---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: empty
  namespace: metallb-system
